#!/bin/bash
set -ue

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE USER ${STELLAR_DB_USER} WITH PASSWORD '${STELLAR_DB_PASSWORD}';
    CREATE DATABASE core;
    CREATE DATABASE horizon;
    GRANT ALL PRIVILEGES ON DATABASE core TO ${STELLAR_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE horizon TO ${STELLAR_DB_USER};
EOSQL